export const TOGGLE_RANDOM_HOUSE = 'TOGGLE_RANDOM_HOUSE';
export const ADD_PERSON = 'ADD_PERSON';
export const CHANGE_FORM_VALUE = 'CHANGE_FORM_VALUE';
export const CHANGE_FORM_OPTION = 'CHANGE_FORM_OPTION';
export const DELETE_ITEM = 'DELETE_ITEM';
